
#https://stackoverflow.com/questions/39501417/how-can-i-connect-coveralls-and-travis-in-github

language: php

install:
- composer install --no-interaction

script: 
- mkdir -p build/logs
- vendor/bin/phpunit tests --coverage-clover build/logs/clover.xml

after_success:
- travis_retry php vendor/bin/php-coveralls
