
#Set language
language: php

#Set versions

#Install composer and require coveralls package
#https://gist.github.com/khaosdoctor/5f6989c4fc27ecc03955
install:
  	- composer install --no-interaction
 	- composer require satooshi/php-coveralls:~1.0@stable # Require phpCoveralls

# Build Script. Notice: We are demanding unit to generate a clover file to our previously created folder
script: 
	- phpunit --coverage-clover build/logs/clover.xml --test-suffix .php --colors --report-useless-tests tests/test.php

# After success, run sh to bind coveralls
after_success:
	- sh -c 'if( [ "$TRAVIS_PHP_VERSION" != "hhvm" ] ); then php vendor/bin/coveralls -v; fi;'
