
#http://kizu514.com/blog/setting-up-coveralls-io-with-travis-ci-and-phpunit/

language: php

before_install:
- composer install --dev
- composer require satooshi/php-coveralls:~1.0@stable # Require phpCoveralls

install:
- composer install --no-interaction

script:
- ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml
 
after_script:
- php vendor/bin/coveralls -v
