
#http://kizu514.com/blog/setting-up-coveralls-io-with-travis-ci-and-phpunit/

language: php

before_install:
- composer install
- composer require satooshi/php-coveralls:~1.0@stable # Require phpCoveralls

install:
- composer install --no-interaction

script: "sbt clean coverage test"

after_success: "sbt coveralls"
