
#Set language
language: php

#Set versions

#Install composer and require coveralls package
#https://gist.github.com/khaosdoctor/5f6989c4fc27ecc03955
install:
- composer install --no-interaction
- composer require satooshi/php-coveralls:~1.0@stable

# After success, run sh to bind coveralls
after_success:
- sh -c 'if( [ "$TRAVIS_PHP_VERSION" != "hhvm" ] ); then php vendor/bin/coveralls -v; fi;'
